services:
  db-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cronis.vehiclecontrol.mssql
    ports: 
      - 14333:1433
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=S@cr#t1_01"
      - "MSSQL_PID=Evaluation"
    networks:
      - live-network
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets

  cronis.vehiclecontrol.api:
    image: cronis.vehiclecontrol.api
    container_name: cronis.vehiclecontrol.api
    build:
      context: .
      dockerfile: .\Cronis.VehicleControl.Api\Dockerfile
    ports: 
      - 8180:8180
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8180
    networks:
      - live-network
    depends_on: 
      - db-sqlserver

networks:
  live-network:
    driver: bridge

