// <auto-generated />
using System;
using Cronis.VehicleControl.Infra.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cronis.VehicleControl.Infra.Migrations
{
    [DbContext(typeof(ExcContext))]
    [Migration("20250125184317_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cronis.VehicleControl.Domain.Model.Entities.CheckList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehiclePlate", "StartDateTime")
                        .IsUnique();

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("Cronis.VehicleControl.Domain.Model.Entities.CheckListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Approved")
                        .HasColumnType("bit");

                    b.Property<Guid>("CheckListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CheckListOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CheckListId");

                    b.HasIndex("CheckListOptionId");

                    b.ToTable("CheckListItem");
                });

            modelBuilder.Entity("Cronis.VehicleControl.Domain.Model.Entities.CheckListOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CheckListOption");
                });

            modelBuilder.Entity("Cronis.VehicleControl.Domain.Model.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Cronis.VehicleControl.Domain.Model.Entities.CheckList", b =>
                {
                    b.HasOne("Cronis.VehicleControl.Domain.Model.Entities.User", "User")
                        .WithMany("CheckLists")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cronis.VehicleControl.Domain.Model.Entities.CheckListItem", b =>
                {
                    b.HasOne("Cronis.VehicleControl.Domain.Model.Entities.CheckList", "CheckList")
                        .WithMany("CheckListItems")
                        .HasForeignKey("CheckListId")
                        .IsRequired();

                    b.HasOne("Cronis.VehicleControl.Domain.Model.Entities.CheckListOption", "CheckListOption")
                        .WithMany("CheckListItems")
                        .HasForeignKey("CheckListOptionId")
                        .IsRequired();

                    b.Navigation("CheckList");

                    b.Navigation("CheckListOption");
                });

            modelBuilder.Entity("Cronis.VehicleControl.Domain.Model.Entities.CheckList", b =>
                {
                    b.Navigation("CheckListItems");
                });

            modelBuilder.Entity("Cronis.VehicleControl.Domain.Model.Entities.CheckListOption", b =>
                {
                    b.Navigation("CheckListItems");
                });

            modelBuilder.Entity("Cronis.VehicleControl.Domain.Model.Entities.User", b =>
                {
                    b.Navigation("CheckLists");
                });
#pragma warning restore 612, 618
        }
    }
}
